import Head from 'next/head'
import { ReactNode } from 'react'
import { AuthShowcase } from './AuthShowcase'
import { Sidebar } from './Sidebar'

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Splitville</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex max-w-4xl mx-auto'>
        <Sidebar />
        <main className='container flex flex-col items-center min-h-screen py-16 mx-auto'>
          <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
            Splitville
          </h1>
          <AuthShowcase />
          {children}
        </main>
      </div>
    </>
  )
}
